In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2 = np.array(['apple', 'banana', 'cherry'])
arr3 = np.array([1, 2, 3, 4], dtype='S')



print(arr.dtype) 
print(arr2.dtype, "==> U - unicode string") 
print(arr3)
print(arr3.dtype, " ==> S - string")

int32
<U6 ==> U - unicode string
[b'1' b'2' b'3' b'4']
|S1  ==> S - string


In [13]:
import numpy as np

arr4 = np.array([1, 2, 3, 4], dtype='i4')
print("The size you define expected data type,you can also match the array you define it for in size")
print(arr4)
print(arr4.dtype) 

The size you define expected data type,you can asl match the array you define it for in size
[1 2 3 4]
int32


In [20]:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

# astype() for converting, dtype for when you wanna accept a certain type of data in the array 

arr5 = np.array([1.1, 2.1, 3.1])

newarr = arr5.astype('i')

newarr2 = arr5.astype(int)

newarr3 = arr5.astype(bool)

print(arr5, arr5.dtype)
print(newarr, newarr.dtype)
print(newarr2, newarr2.dtype)
print(newarr3, newarr.dtype)

[1.1 2.1 3.1] float64
[1 2 3] int32
[1 2 3] int32
[ True  True  True] int32


In [26]:
# copy owns the data
arr6 = np.array([1, 2, 3, 4, 5])
x = arr6.copy()
arr6[0] = 42

# will not affect the original data
print(arr6)
print(x) 

# view doesn't own the data
arr7 = np.array([1, 2, 3, 4, 5])
x2 = arr7.view()
arr7[0] = 42

# will affect the orginal data
print(arr7)
print(x2)

# changing both by changing the original, with view 
arr8 = np.array([1, 2, 3, 4, 5])
x3 = arr8.view()
x3[0] = 31

print(arr8)
print(x3) 

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
[31  2  3  4  5]
[31  2  3  4  5]


In [28]:
# Every NumPy array has the attribute base that returns None if the array owns the data.

# Otherwise, the base  attribute refers to the original object. 

arr9 = np.array([1, 2, 3, 4, 5])

a = arr.copy()
b = arr.view()

print(a.base, " ==> copy, owns the data")
print(b.base, " ==> view, doesn't own the data, refers to the original") 

None  ==> copy, owns the data
[31  2  3  4]  ==> view, doesn't own the data, refers to the original


In [32]:
arr10 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr10.shape, "2 dimensions, each dimension has 4 elements") 

(2, 4) 2 dimensions, each dimension has 4 elements


In [35]:
# ndmin is used to create the 5 dimensions
arr11 = np.array([1, 2, 3, 4], ndmin=5)

print(arr11)
print('shape of array :', arr11.shape, "apparently we can say that (4 + 1)th dimension has 4 elements for this one") 

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4) apparently we can say that (4 + 1)th dimension has 4 elements for this one


In [37]:
arr12 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr4 = arr12.reshape(4, 3)

print(newarr4)
print(newarr4.base, "base will return the original")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
# You are allowed to have one "unknown" dimension.
# Pass -1 as the value, and NumPy will calculate this number for you.

arr13 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr5 = arr13.reshape(2, 2, -1)

print(newarr5) 
# We can not pass -1 to more than one dimension.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
# reshape(-1) can be used to flatten
arr14 = np.array([[1, 2, 3], [4, 5, 6]])

newarr6 = arr14.reshape(-1)

print(newarr6) 

[1 2 3 4 5 6]
