In [14]:
import numpy as np
csvdata.head()


NameError: name 'csvdata' is not defined

In [15]:
test5 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("From the second element, slice elements from index 1 to index 4 (not included):", test5[1, 1:4]) 
print("From both elements return the index 2:" ,test5[0:2, 2]) 
print(test5[0:2, 1:4]) 

From the second element, slice elements from index 1 to index 4 (not included): [7 8 9]
From both elements return the index 2: [3 8]
[[2 3 4]
 [7 8 9]]


In [14]:
csvdata.head(6)

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   
5  5             Charmeleon   Fire     NaN    405  58      64       58   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False  
5       80       65     80           1      False

In [ ]:
import numpy as np

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

In [19]:
print(np.__version__)

1.20.1


In [22]:
print("an array is called ndarray and type is ", type(arr), "in python")

an array is called ndarray and type is  <class 'numpy.ndarray'> in python


In [23]:
test42 = np.array(42)

print(test) 

42


In [24]:
print(type(test42))

<class 'numpy.ndarray'>


In [25]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [26]:
arr5d = np.array([1, 2, 3, 4], ndmin=5)

print(arr5d)
print('number of dimensions :', arr5d.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [29]:
print(arr5d[0][0][0][0][0])

1


In [30]:
test1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', test1[0, 1]) 

2nd element on 1st dim:  2


In [31]:
test2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(test2[0, 1, 2]) 

6


In [32]:
test3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', test3[1, -1]) 

Last element from 2nd dim:  10


In [45]:
test4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(test4[1:5], "end is not included") 
print(test4[1:], "starting from the second till the last one, last one's included")
print(test4[:4], "until the fourth") 
print(test4[-3:-1], "in reverse") 
print(test4[::2], "go 2 by 2") 
print(test4[1:8:2], "simple steps") 

[2 3 4 5] end is not included
[ 2  3  4  5  6  7  8  9 10] starting from the second till the last one, last one's included
[1 2 3 4] until the fourth
[8 9] in reverse
[1 3 5 7 9]
[2 4 6 8] simple steps
